### ISSUE TITLE
Calling needs :cxx11 is disabled! There is no replacement.

### ISSUE THREAD

**Issue by genevera** [david0/homebrew-audio#19]
Got an error this morning:

```bash
Error: Failed to import: /usr/local/Homebrew/Library/Taps/david0/homebrew-audio/Formula/ardour4.rb
Calling needs :cxx11 is disabled! There is no replacement.
Please report this to the david0/audio tap:
  /usr/local/Homebrew/Library/Taps/david0/homebrew-audio/Formula/ardour4.rb:47

Error: Failed to import: /usr/local/Homebrew/Library/Taps/david0/homebrew-audio/Formula/ardour5.rb
Calling needs :cxx11 is disabled! There is no replacement.
Please report this to the david0/audio tap:
  /usr/local/Homebrew/Library/Taps/david0/homebrew-audio/Formula/ardour5.rb:45
```

**Comment by lucacicinelli** [comment]
Same issue!

`brew tap david0/homebrew-audio
==> Tapping david0/audio
Cloning into '/usr/local/Homebrew/Library/Taps/david0/homebrew-audio'...
remote: Enumerating objects: 26, done.
remote: Counting objects: 100% (26/26), done.
remote: Compressing objects: 100% (26/26), done.
remote: Total 26 (delta 1), reused 12 (delta 0), pack-reused 0
Unpacking objects: 100% (26/26), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/david0/homebrew-audio/Formula/ardour5.rb
Calling needs :cxx11 is disabled! There is no replacement.
Please report this to the david0/audio tap:
  /usr/local/Homebrew/Library/Taps/david0/homebrew-audio/Formula/ardour5.rb:45

Error: Invalid formula: /usr/local/Homebrew/Library/Taps/david0/homebrew-audio/Formula/ardour4.rb
Calling needs :cxx11 is disabled! There is no replacement.
Please report this to the david0/audio tap:
  /usr/local/Homebrew/Library/Taps/david0/homebrew-audio/Formula/ardour4.rb:47

Error: Cannot tap david0/audio: invalid syntax in tap!`

**Comment by ghost** [comment]
Same issue here. I did make a fork to fabthink/homebrew-audio and the tap worked so far:

`brew tap fabthink/homebrew-audio`

The next step did not yet work due to an outdated XCode... (trying to fix this later)

`brew install --HEAD calf`

> iFabPro:~ fab$ brew install --HEAD calf
> ==> Installing calf from fabthink/audio
> Error: Your Xcode (9.3) is too outdated.
> Please update to Xcode 10.1 (or delete it).
> Xcode can be updated from the App Store.

**Comment by lucacicinelli** [comment]
Sorry, but ardour5 won't work.

**Comment by ghost** [comment]
oh, that is sad...
