### ISSUE TITLE
lv2vst won't install on macOS 10.15.4

### ISSUE THREAD

**Issue by plutek** [david0/homebrew-audio#21]
here's what i'm seeing when attempting to install lv2vst on a new mac mini:
---------------------------------
brew install --HEAD david0/audio/lv2vst 
==> Installing lv2vst from david0/audio
==> Installing dependencies for david0/audio/lv2vst: make
==> Installing david0/audio/lv2vst dependency: make
==> Downloading https://homebrew.bintray.com/bottles/make-4.3.catalina.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/b2/b2cbb6b854495469de4d065825c94540ad3053a1ff7c1832f4eb7781ee6b8231?__gda__=exp=158886
######################################################################## 100.0%
==> Pouring make-4.3.catalina.bottle.tar.gz
==> Caveats
GNU "make" has been installed as "gmake".
If you need to use it as "make", you can add a "gnubin" directory
to your PATH from your bashrc like:

    PATH="/usr/local/opt/make/libexec/gnubin:$PATH"
==> Summary
🍺  /usr/local/Cellar/make/4.3: 15 files, 1MB
==> Installing david0/audio/lv2vst --HEAD
==> Cloning https://github.com/x42/lv2vst.git
Cloning into '/Users/plutek/Library/Caches/Homebrew/lv2vst--git'...
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
==> make osxbundle
Last 15 lines from /Users/plutek/Library/Logs/Homebrew/lv2vst/01.make:
      _lilv_expand in util-e26fa0.o
      _lilv_path_join in util-e26fa0.o
      ...
  "_strdup", referenced from:
      load_file(char const*) in instantiate-04112a.o
      LV2Parser::parse(char const*) in lv2ttl-55e699.o
      node_strdup(LilvNodeImpl*) in lv2ttl-55e699.o
      file_strdup(LilvNodeImpl const*) in lv2ttl-55e699.o
      Lv2UriMap::uri_to_id(char const*) in lv2vst-de8401.o
      LV2Vst::get_chunk(void**, bool) in state-90ee70.o
     (maybe you meant: _lilv_strdup)
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [lv2vst.dylib] Error 1
make: *** [lv2vst.i386.dylib] Error 2
--------------------------------

...any ideas on a fix?

many thanks... cheers!
.pltk.

**Comment by david0** [comment]
I updated the formula to build just the 64bit version. Catalina does not support 32bit anymore. Feel free to re-open this issue if the problem still exists!
