### ISSUE TITLE
OS X install error (OS X v10.11.6)

### ISSUE THREAD

**Issue by tteague** [david0/homebrew-audio#4]
I'm trying to install under OS X and getting the following error. I'm very comfortable with the system and I would be happy to provide any files you would like. I checked 01.autogen.sh and config.log and didn't see any errors. I am trying to use your plugins with Mixbus.

Thanks,
Tim Teague

brew install --HEAD calf
==> Installing calf from david0/audio
==> Installing dependencies for david0/audio/calf: libpng
==> Installing david0/audio/calf dependency: libpng
==> Downloading https://homebrew.bintray.com/bottles/libpng-1.6.25.el_capitan.bottle.tar.gz
###### ################################################################## 100.0%

==> Pouring libpng-1.6.25.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/libpng/1.6.25: 25 files, 1.2M
==> Installing david0/audio/calf
==> Cloning https://github.com/calf-studio-gear/calf.git
Updating /Users/tim/Library/Caches/Homebrew/calf--git
==> Checking out branch master
==> Downloading https://github.com/david0/calf/commit/d2f174083d97ce0f6930fc28764fdec80810f464.patch
Already downloaded: /Users/tim/Library/Caches/Homebrew/calf--patch-e63a29017ce1cfff2a374f48fc3f2d99463851e88e5462aa5bc6475a870124f7.patch
==> Patching
==> Applying d2f174083d97ce0f6930fc28764fdec80810f464.patch
patching file configure.ac
patching file src/Makefile.am
==> ./autogen.sh --disable-dependency-tracking --prefix=/usr/local/Cellar/calf/HEAD-e7daf55 --with-lv2-dir=/u
==> make install
Last 15 lines from /Users/tim/Library/Logs/Homebrew/calf/02.make:
min(const _Tp& __a, const _Tp& __b, _Compare __comp)
^
2 errors generated.
make[2]: **\* [modules_limit.lo] Error 1
make[2]: **\* Waiting for unfinished jobs....
2 errors generated.
make[2]: **\* [analyzer.lo] Error 1
libtool: compile:  clang++ -DHAVE_CONFIG_H -I. -I.. -I.. -I. -ffast-math -finline-limit=80 -I/usr/local/Cellar/fluid-synth/1.1.6/include -I/usr/local/Cellar/lv2/1.12.0/include -D_REENTRANT -I/usr/local/Cellar/pcre/8.39/include -I/usr/local/Cellar/glib/2.48.2/include/glib-2.0 -I/usr/local/Cellar/glib/2.48.2/lib/glib-2.0/include -I/usr/local/opt/gettext/include -g -O2 -O3 -finline-functions -finline-functions-called-once -Wall -c lv2wrap.cpp -o lv2wrap.o >/dev/null 2>&1
libtool: compile:  clang++ -DHAVE_CONFIG_H -I. -I.. -I.. -I. -ffast-math -finline-limit=80 -I/usr/local/Cellar/fluid-synth/1.1.6/include -I/usr/local/Cellar/lv2/1.12.0/include -D_REENTRANT -I/usr/local/Cellar/pcre/8.39/include -I/usr/local/Cellar/glib/2.48.2/include/glib-2.0 -I/usr/local/Cellar/glib/2.48.2/lib/glib-2.0/include -I/usr/local/opt/gettext/include -g -O2 -O3 -finline-functions -finline-functions-called-once -Wall -c audio_fx.cpp -o audio_fx.o >/dev/null 2>&1
libtool: compile:  clang++ -DHAVE_CONFIG_H -I. -I.. -I.. -I. -ffast-math -finline-limit=80 -I/usr/local/Cellar/fluid-synth/1.1.6/include -I/usr/local/Cellar/lv2/1.12.0/include -D_REENTRANT -I/usr/local/Cellar/pcre/8.39/include -I/usr/local/Cellar/glib/2.48.2/include/glib-2.0 -I/usr/local/Cellar/glib/2.48.2/lib/glib-2.0/include -I/usr/local/opt/gettext/include -g -O2 -O3 -finline-functions -finline-functions-called-once -Wall -c modules_delay.cpp -o modules_delay.o >/dev/null 2>&1
libtool: compile:  clang++ -DHAVE_CONFIG_H -I. -I.. -I.. -I. -ffast-math -finline-limit=80 -I/usr/local/Cellar/fluid-synth/1.1.6/include -I/usr/local/Cellar/lv2/1.12.0/include -D_REENTRANT -I/usr/local/Cellar/pcre/8.39/include -I/usr/local/Cellar/glib/2.48.2/include/glib-2.0 -I/usr/local/Cellar/glib/2.48.2/lib/glib-2.0/include -I/usr/local/opt/gettext/include -g -O2 -O3 -finline-functions -finline-functions-called-once -Wall -c modules_tools.cpp -o modules_tools.o >/dev/null 2>&1
libtool: compile:  clang++ -DHAVE_CONFIG_H -I. -I.. -I.. -I. -ffast-math -finline-limit=80 -I/usr/local/Cellar/fluid-synth/1.1.6/include -I/usr/local/Cellar/lv2/1.12.0/include -D_REENTRANT -I/usr/local/Cellar/pcre/8.39/include -I/usr/local/Cellar/glib/2.48.2/include/glib-2.0 -I/usr/local/Cellar/glib/2.48.2/lib/glib-2.0/include -I/usr/local/opt/gettext/include -g -O2 -O3 -finline-functions -finline-functions-called-once -Wall -c metadata.cpp -o metadata.o >/dev/null 2>&1
libtool: compile:  clang++ -DHAVE_CONFIG_H -I. -I.. -I.. -I. -ffast-math -finline-limit=80 -I/usr/local/Cellar/fluid-synth/1.1.6/include -I/usr/local/Cellar/lv2/1.12.0/include -D_REENTRANT -I/usr/local/Cellar/pcre/8.39/include -I/usr/local/Cellar/glib/2.48.2/include/glib-2.0 -I/usr/local/Cellar/glib/2.48.2/lib/glib-2.0/include -I/usr/local/opt/gettext/include -g -O2 -O3 -finline-functions -finline-functions-called-once -Wall -c modules_comp.cpp -o modules_comp.o >/dev/null 2>&1
make[1]: **\* [install-recursive] Error 1
make: **\* [install-recursive] Error 1

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/david0/homebrew-audio/issues

**Comment by david0** [comment]
Sorry, can not check this in detail this week. But it sounds like the problem that I already reported to calf https://github.com/calf-studio-gear/calf/issues/94

Building without --HEAD should work.

**Comment by tteague** [comment]
```
David, that was the right solution. 

Thanks for helping me out,
Tim

On 9/13/16 12:35 AM, David wrote:


  Sorry, can not check this in detail this week. But it sounds
    like the problem that I already reported to calf calf-studio-gear/calf#94
  Building without --HEAD should work.
  —
    You are receiving this because you authored the thread.
    Reply to this email directly, view
      it on GitHub, or mute
      the thread.







  {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/david0/homebrew-audio","title":"david0/homebrew-audio","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/david0/homebrew-audio"}},"updates":{"snippets":[{"icon":"PERSON","message":"@david0 in #4: Sorry, can not check this in detail this week. But it sounds like the problem that I already reported to calf https://github.com/calf-studio-gear/calf/issues/94\r\n\r\nBuilding without --HEAD should work."}],"action":{"name":"View Issue","url":"https://github.com/david0/homebrew-audio/issues/4#issuecomment-246599923"}}}</scri
```

 pt>
</body>
</html>
</html></blockquote>
    <br>
  </body>
</html>

**Comment by david0** [comment]
Fixed in upstream
