### ISSUE TITLE
Ardour4 compile error on Sierra

### ISSUE THREAD

**Issue by stateisbad** [david0/homebrew-audio#8]
Hello,

I'm running into the following compile error for Ardour4 on OSX Sierra:

../libs/ardour/lv2_plugin.cc:2268:23: warning: cast from 'uint8_t *' (aka 'unsigned char *') to 'LV2_Atom *' increases required alignment from 1 to 4 [-Wcast-align]
                                        LV2_Atom* atom = (LV2_Atom*)(data - sizeof(LV2_Atom));
                                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../libs/ardour/audio_unit.cc:737:12: warning: 24 enumeration values not handled in switch: 'kAudioUnitParameterUnit_Generic', 'kAudioUnitParameterUnit_Indexed', 'kAudioUnitParameterUnit_Boolean'... [-Wswitch]
                        switch (info.unit) {
                                ^
12 warnings generated.
9 warnings generated.
Waf: Leaving directory `/private/tmp/ardour4-20170125-7579-20rv8j/ardour-4.7/build'
Build failed
 -> task in 'libgtkmm2ext' failed (exit status 1):
	{task 4343592400: cxx actions.cc -> actions.cc.1.o}
['clang++', '-I/private/tmp/ardour4-20170125-7579-20rv8j/ardour-4.7', '-DHAVE_RF64_RIFF', '-DWAF_BUILD', '-g', '-fshow-column', '-DARCH_X86', '-DBUILD_VECLIB_OPTIMIZATIONS', '-DMAC_OS_X_VERSION_MAX_ALLOWED=1090', '-mmacosx-version-min=10.8', '-Wall', '-Wpointer-arith', '-Wcast-qual', '-Wcast-align', '-Wno-unused-parameter', '-DBOOST_SYSTEM_NO_DEPRECATED', '-D_ISOC9X_SOURCE', '-D_LARGEFILE64_SOURCE', '-D_FILE_OFFSET_BITS=64', '-DENABLE_NLS', '-DPROGRAM_NAME="Ardour"', u'-DPROGRAM_VERSION="4"', '--stdlib=libc++', '-Wno-c++11-narrowing', '-Qunused-arguments', '-Woverloaded-virtual', '-Wno-mismatched-tags', '-D__STDC_LIMIT_MACROS', '-D__STDC_FORMAT_MACROS', '-DCANVAS_COMPATIBILITY', '-DCANVAS_DEBUG', '-fPIC', '-compatibility_version', '1', '-current_version', '1', '-fPIC', '-compatibility_version', '1', '-current_version', '1', '-msse', '-msse2', '-F/System/Library/Frameworks', '-F/Library/Frameworks', '-DAUDIOUNIT_SUPPORT', '-I/private/tmp/ardour4-20170125-7579-20rv8j/ardour-4.7/build/libs/gtkmm2ext', '-I/private/tmp/ardour4-20170125-7579-20rv8j/ardour-4.7/libs/gtkmm2ext', '-I/private/tmp/ardour4-20170125-7579-20rv8j/ardour-4.7/build/libs/ardour', '-I/private/tmp/ardour4-20170125-7579-20rv8j/ardour-4.7/libs/ardour', '-I/private/tmp/ardour4-20170125-7579-20rv8j/ardour-4.7/build/libs/midi++2', '-I/private/tmp/ardour4-20170125-7579-20rv8j/ardour-4.7/libs/midi++2', '-I/private/tmp/ardour4-20170125-7579-20rv8j/ardour-4.7/build/libs/evoral', '-I/private/tmp/ardour4-20170125-7579-20rv8j/ardour-4.7/libs/evoral', '-I/private/tmp/ardour4-20170125-7579-20rv8j/ardour-4.7/build/libs/audiographer', '-I/private/tmp/ardour4-20170125-7579-20rv8j/ardour-4.7/libs/audiographer', '-I/private/tmp/ardour4-20170125-7579-20rv8j/ardour-4.7/build/libs/audiographer/src', '-I/private/tmp/ardour4-20170125-7579-20rv8j/ardour-4.7/libs/audiographer/src', '-I/private/tmp/ardour4-20170125-7579-20rv8j/ardour-4.7/build/libs/pbd', '-I/private/tmp/ardour4-20170125-7579-20rv8j/ardour-4.7/libs/pbd', '-I/private/tmp/ardour4-20170125-7579-20rv8j/ardour-4.7/build/libs/evoral/src/libsmf', '-I/private/tmp/ardour4-20170125-7579-20rv8j/ardour-4.7/libs/evoral/src/libsmf', '-I/private/tmp/ardour4-20170125-7579-20rv8j/ardour-4.7/build/libs/timecode', '-I/private/tmp/ardour4-20170125-7579-20rv8j/ardour-4.7/libs/timecode', '-I/private/tmp/ardour4-20170125-7579-20rv8j/ardour-4.7/build/libs/libltc/ltc', '-I/private/tmp/ardour4-20170125-7579-20rv8j/ardour-4.7/libs/libltc/ltc', '-I/private/tmp/ardour4-20170125-7579-20rv8j/ardour-4.7/build/libs/appleutility/CoreAudio/PublicUtility', '-I/private/tmp/ardour4-20170125-7579-20rv8j/ardour-4.7/libs/appleutility/CoreAudio/PublicUtility', '-I/usr/local/Cellar/libpng/1.6.28/include/libpng16', '-I/usr/local/opt/freetype/include/freetype2', '-I/usr/local/Cellar/fontconfig/2.12.1_2/include', '-I/usr/local/Cellar/pixman/0.34.0/include/pixman-1', '-I/usr/local/Cellar/pcre/8.39/include', '-I/usr/local/Cellar/glib/2.50.2/include/glib-2.0', '-I/usr/local/Cellar/glib/2.50.2/lib/glib-2.0/include', '-I/usr/local/opt/gettext/include', '-I/usr/local/Cellar/cairo/1.14.8/include/cairo', '-I/usr/local/Cellar/gdk-pixbuf/2.36.2/include/gdk-pixbuf-2.0', '-I/usr/local/Cellar/atk/2.22.0/include/atk-1.0', '-I/usr/local/Cellar/harfbuzz/1.4.2/include/harfbuzz', '-I/usr/local/Cellar/pango/1.40.3/include/pango-1.0', '-I/usr/local/Cellar/gtk+/2.24.31_1/include/gtk-unix-print-2.0', '-I/usr/local/Cellar/gtk+/2.24.31_1/include/gtk-2.0', '-I/usr/local/Cellar/gtk+/2.24.31_1/lib/gtk-2.0/include', '-I/usr/local/Cellar/libsigc++/2.10.0/include/sigc++-2.0', '-I/usr/local/Cellar/libsigc++/2.10.0/lib/sigc++-2.0/include', '-I/usr/local/Cellar/glibmm/2.50.0/include/giomm-2.4', '-I/usr/local/Cellar/glibmm/2.50.0/lib/giomm-2.4/include', '-I/usr/local/Cellar/glibmm/2.50.0/include/glibmm-2.4', '-I/usr/local/Cellar/glibmm/2.50.0/lib/glibmm-2.4/include', '-I/usr/local/Cellar/cairomm/1.12.2/include/cairomm-1.0', '-I/usr/local/Cellar/cairomm/1.12.2/lib/cairomm-1.0/include', '-I/usr/local/Cellar/pangomm/2.40.1/include/pangomm-1.4', '-I/usr/local/Cellar/pangomm/2.40.1/lib/pangomm-1.4/include', '-I/usr/local/Cellar/atkmm/2.24.2/include/atkmm-1.6', '-I/usr/local/Cellar/gtkmm/2.24.5/include/gtkmm-2.4', '-I/usr/local/Cellar/gtkmm/2.24.5/lib/gtkmm-2.4/include', '-I/usr/local/Cellar/gtkmm/2.24.5/include/gdkmm-2.4', '-I/usr/local/Cellar/gtkmm/2.24.5/lib/gdkmm-2.4/include', '-I/usr/include/libxml2', '-I/usr/local/Cellar/libsndfile/1.0.26/include', '-I/usr/local/Cellar/aubio/0.4.4/include', '-I/usr/local/Cellar/libsamplerate/0.1.9/include', '-I/usr/local/Cellar/raptor/2.0.15/include/raptor2', '-I/usr/local/Cellar/lrdf/0.6.1/include', '-I/usr/local/Cellar/taglib/1.11.1/include/taglib', '-I/usr/local/Cellar/vamp-plugin-sdk/2.6/include', '-I/usr/local/opt/rubberband/include', '-I/usr/local/Cellar/lv2/1.12.0/include', '-I/usr/local/Cellar/serd/0.26.0/include/serd-0', '-I/usr/local/Cellar/sord/0.16.0/include/sord-0', '-I/usr/local/Cellar/sratom/0.4.6/include/sratom-0', '-I/usr/local/Cellar/lilv/0.22.0/include/lilv-0', '-I/usr/local/Cellar/suil/0.8.2/include/suil-0', '-I/usr/local/Cellar/fftw/3.3.6-pl1/include', '-I/private/tmp/ardour4-20170125-7579-20rv8j/ardour-4.7/build', '-DNEED_INTL=1', '-DHAVE_COREAUDIO=1', '-DAUDIOUNIT_SUPPORT=1', '-DGTKOSX=1', '-DTOP_MENUBAR=1', '-DINTERNAL_SHARED_LIBS=1', '-DHAVE_DLOPEN=1', '-DHAVE_GLIB=1', '-DHAVE_GTHREAD=1', '-DHAVE_GLIBMM=1', '-DHAVE_SNDFILE=1', '-DHAVE_GIOMM=1', '-DHAVE_CURL=1', '-DHAVE_LO=1', '-DHAVE_TAGLIB=1', '-DHAVE_VAMPSDK=1', '-DHAVE_VAMPHOSTSDK=1', '-DHAVE_RUBBERBAND=1', '-DEXPORT_VISIBILITY_HIDDEN=False', '-DPHONE_HOME=1', '-DENABLE_NLS=1', '-DCONFIG_ARCH="x86_64"', '-DHAVE_LIBS_APPLEUTILITY=1', '-DHAVE_LIBS_CLEARLOOKS_NEWER=1', '-DHAVE_LIBS_QM_DSP=1', '-DHAVE_FFTW3F=1', '-DHAVE_AUBIO=1', '-DHAVE_AUBIO4=1', '-DHAVE_LIBS_VAMP_PLUGINS=1', '-DHAVE_LIBS_LIBLTC=1', '-DHAVE_LIBS_PTFORMAT=1', '-DHAVE_XML=1', '-DHAVE_SIGCPP=1', '-DHAVE_EXECINFO=1', '-DHAVE_POSIX_MEMALIGN=1', '-DHAVE_LOCALTIME_R=1', '-DHAVE_LIBS_PBD=1', '-DHAVE_LIBS_MIDIPP2=1', '-DHAVE_LIBS_EVORAL=1', '-DHAVE_CONTROL_PROTOCOL=1', '-DHAVE_FADERPORT=1', '-DHAVE_GENERIC_MIDI=1', '-DHAVE_MACKIE=1', '-DHAVE_LIBS_SURFACES=1', '-DHAVE_2IN2OUT=1', '-DHAVE_1IN2OUT=1', '-DHAVE_VBAP=1', '-DHAVE_STEREOBALANCE=1', '-DHAVE_LIBS_PANNERS=1', '-DHAVE_JACK=1', '-DHAVE_JACK_METADATA=1', '-DHAVE_LIBS_BACKENDS=1', '-DHAVE_LIBS_TIMECODE=1', '-DHAVE_LRDF=1', '-DHAVE_SAMPLERATE=1', '-DHAVE_LV2=1', '-DHAVE_LV2_1_2_0=1', '-DHAVE_LV2_1_10_0=1', '-DHAVE_SERD=1', '-DHAVE_SORD=1', '-DHAVE_SRATOM=1', '-DHAVE_LILV=1', '-DHAVE_LILV_0_16_0=1', '-DHAVE_LILV_0_19_2=1', '-DHAVE_LILV_0_21_3=1', '-DHAVE_SUIL=1', '-DLV2_SUPPORT=1', '-DHAVE_OGG=1', '-DHAVE_FLAC=1', '-DUSE_RUBBERBAND=1', '-DCURRENT_SESSION_FILE_VERSION=3001', '-DHAVE_SYS_STATVFS_H=1', '-DHAVE_UNISTD=1', '-DHAVE_BOOST_SCOPED_PTR_HPP=1', '-DHAVE_BOOST_PTR_CONTAINER_PTR_LIST_HPP=1', '-DHAVE_LIBS_ARDOUR=1', '-DHAVE_GTKMM=1', '-DHAVE_GTK=1', '-DHAVE_LIBS_GTKMM2EXT=1', '-DHAVE_FFTW35F=1', '-DHAVE_BOOST_FORMAT_HPP=1', '-DHAVE_LIBS_AUDIOGRAPHER=1', '-DHAVE_CAIROMM=1', '-DHAVE_LIBS_CANVAS=1', '-DHAVE_LV2_1_0_0=1', '-DHAVE_LIBS_PLUGINS_REASONABLESYNTH_LV2=1', '-DHAVE_FONTCONFIG=1', '-DHAVE_BOOST_SHARED_PTR_HPP=1', '-DHAVE_BOOST_WEAK_PTR_HPP=1', '-DHAVE_GTK2_ARDOUR=1', '-DHAVE_EXPORT=1', '-DHAVE_MIDI_MAPS=1', '-DHAVE_MCP=1', '-DHAVE_PATCHFILES=1', '-DHAVE_HEADLESS=1', '-DHAVE_SESSION_UTILS=1', '-DHAVE_LIBS_FST=1', '-DHAVE_LIBS_VFORK=1', '-DHAVE_LIBS_ARDOURALSAUTIL=1', '-DHAVE_CFGTOOL=1', '-DLIBGTKMM2EXT_DLL_EXPORTS', '-DABSTRACT_UI_EXPORTS', '-DPACKAGE="gtkmm2ext3"', u'-DLOCALEDIR="/usr/local/Cellar/ardour4/4.7/share/ardour4/locale"', '-D_REENTRANT', '-D_REENTRANT', '-D_REENTRANT', '-D_REENTRANT', '-D_REENTRANT', '-D_REENTRANT', '../libs/gtkmm2ext/actions.cc', '-c', '-o', 'libs/gtkmm2ext/actions.cc.1.o']
Using packaged revision

I did try the Ardour5 formula, but that gave me the same error as issue #7.  I run Ardour4 on another Linux machine, so the Ardour4 formula would be great to have working.  Any help would be appreciated, thanks!

**Comment by david0** [comment]
Sorry I don't have Sierra. Does https://github.com/david0/homebrew-audio/pull/6 work for you?

**Comment by stateisbad** [comment]
@david0, unfortunately no, it didn't work.  Interestingly enough, I got the same error for both Ardour 4 and 5 formulae with PR #6 (at least the same in the sense that they were both tasks in libcanvas that failed):

```
                                                              (current_request ? current_request->image : 0)));
                                                                               ^ ~~~~~~~~~~~~~~~~~~~~~~   ~
/private/tmp/ardour4-20170209-40870-t4zre9/ardour-4.7/libs/pbd/pbd/debug.h:70:97: note: expanded from macro 'DEBUG_TRACE'
#define DEBUG_TRACE(bits,str) if (((bits) & PBD::debug_bits).any()) { PBD::debug_print (# bits, str); }
                                                                                                ^~~
1 error generated.
Waf: Leaving directory `/private/tmp/ardour4-20170209-40870-t4zre9/ardour-4.7/build'
Build failed
 -> task in 'libcanvas' failed (exit status 1):
	{task 4343169360: cxx stateful_image.cc -> stateful_image.cc.1.o}
```

**Comment by stateisbad** [comment]
Feel free to close this issue. I was able to build Ardour 5 on the latest OSX version, so this issue is obsolete at this point.

**Comment by david0** [comment]
I will close this issue, please open a new pull request to update the ardour formula (i did not try it since a long time)
